---
apiVersion: v1
kind: Service
metadata:
  name: &app homeassistant
  namespace: networking
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: homeassistant
      port: &port 80
      protocol: TCP
      targetPort: 8123
---
apiVersion: v1
kind: Endpoints
metadata:
  name: &app homeassistant
  namespace: networking
subsets:
  - addresses:
      - ip: 192.168.100.52
    ports:
      - name: homeassistant
        port: 8123
        protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app homeassistant
  namespace: networking
  annotations:
    hajimari.io/icon: mdi:robot-vacuum
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  ingressClassName: nginx
  rules:
    - host: &host "ha.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: *app
                port:
                  number: *app
  tls:
    - hosts:
        - *host
