apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:QAZcI9cgF5jdcXeuE+Sinq53JNP/ORMtfNr3BULxatGryDxecHrvsg==,iv:igX4IQ+j/dyaQZIVqWkwFCcIDpvjJ3Zv47395NkftUY=,tag:oBDozWEvCyeDkr2G/XWaiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1egce8jyk8n3647lzxsmzjxyee3v0tty6qc2nntes293u7calqydsjdr3hq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRnFXK21BY3N4VHlYR3k1
            K09ESmlHUWZlWXduWGlkMHUwcFQ3eEt0V1dZCmVZZVJISHppZ2xzditMK1NtOW5T
            UlI0S1IzcXF6N0tlbG91T2llQXE5aGsKLS0tIFFMVWY4NEM0T1pGeEhlSEZ6RnlR
            U2hSN2R0VGR1ZllhUnREckZhVjIzWm8KwfweEm0omSA3Zb3uo8PtHIwr+VZ2qMha
            0Ez8vOAYEZy2XhioXj30tu4uf8ABT9L7ysrKh8rvXzT8k0CsxoaHZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-24T02:36:32Z"
    mac: ENC[AES256_GCM,data:2r2vGC5Ktp1I7SXzOdz4PEHw10xGxKAfWacCnvkfUt3MGLjhZO0FkdrDQPhY9dTgOHXvJ52PX0tls4RBfeik3eSKjYJ7RzGRPTsf/paxk/OPreEE8PJPE37R4baYSgn9zpDWMQeZEsWqpuTxEn98mWVdy3Xx6UFkUGH+8ggT468=,iv:W0eEz9iT865v+/1ywubSJgNMjnCeFeMYZqU360bFZJ8=,tag:rlspB2XQqNNB+T3xxXg4dQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
