apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:ZW/jrIJSyx76aTrO+2qd1jinlZp9swNqwzfg/8AepxaN+cnphQ==,iv:QAa7BP3VlFVJEHVeNB6oNBhLbY8HqZVeugAq/I9LN88=,tag:ikt1e9lJCzqEmAg/kZugwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1egce8jyk8n3647lzxsmzjxyee3v0tty6qc2nntes293u7calqydsjdr3hq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUWd2bWVOSTAyR2dGY1di
            ZnZvSTRYTmVYN3JMUFZpa0pFMDRGOCsyK3hvCjFNU2dUc3JpblNxdlFkYm1uZEhx
            cnpLS2NHMnlrZGx0UDNBWXNCMjF3QzAKLS0tIDM0blhwdi9OV3VxWlVmM1d3alBq
            NGRpS0Q1WFFQbCsxSWNtTDBIUWdZTlkKK45bbDROH8WdwdCPqlTxDrEAcTZfO91u
            b6zN67eULIPYTMcynfPSSgpK9dvvpF9fsQClqVyAwyEng50SspK30g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-24T02:36:32Z"
    mac: ENC[AES256_GCM,data:KcyKSQ9U5+IfglIAUdoBan/73bd9NwlGN0f2u5zIq0xpiRMlm609PvoxPwhSVOvFI+/brizTx5cdMr5HbuQJQHrxl4MIiT2qWX9e2+8cMDv2i4WYr6MS49Mpx014pKrMGaf4FsZaqPXEmPWBgluGA6NdEnQ+zMvpM8SSqBjTVzk=,iv:CLdsZggTb8Zd9JJrWjLakbfkryapGPzhhSjcsf9Ikck=,tag:YMj3LicZVkj8uIjp9tm8kg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
