apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:rVNmrNiAjjPGertDxbXCrpK/i8+e,iv:VKra6x6zRgONQTTb4bYHsYMQEF7bZoCVKjuKtPhXSjo=,tag:Ma6BTwZxmgFdzOvn6cCAiA==,type:str]
    api-key: ENC[AES256_GCM,data:84maIEd5c7UGkk8wHyg5IVnLzOJQbFkTJiULq+kIzoxd/tjm7w==,iv:Pav/vSO90/4oKgRHB397whV/HPkH2K2Ibd35ax5Q6pk=,tag:Q7jF1oe3ZuRqbwPu/FeIMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1egce8jyk8n3647lzxsmzjxyee3v0tty6qc2nntes293u7calqydsjdr3hq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRS0JiQ2V3ZUN6aGZ3RUZV
            TmtWRUM4NDE2RGNtdkJzUFc3eVpDMkVFcGlnClNOSVBaOUdaUVpDQjdhWFRKUEt0
            Y09SUXZ2VmFTQXk1WG05ZUVHdGpVcG8KLS0tIHNCMXdUU0F5b3NEdWcvZDhmVHlK
            YVRyZU9mR3hrNnZ5ZjdEbTN3Si9ra00Kr4WD2sxRAkxF4kEnkzANz+fx2EdvWpNg
            vxxTOoM/S2t8TnM9bSJAiFoE9iLMfuSflGynSFinLjqVooWhuZtpdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-24T02:36:32Z"
    mac: ENC[AES256_GCM,data:Y2ie6RcXK0cBKYw3LXt5vyaG+JQhEhIssq4k0HL2zKtS31eTBU+LThnT31pazn7MLUQW5Eilq5p7SGE0HMHn/DVLOCA48UQI9kIy76TeL1DNZEowIhX+KVAqJvaM9iEOSyOuJ2iJdQQ/XKMGNo91Fy3PBlSU0v7nVfoCbUuW/oc=,iv:WR4feNNAX3u0exTFhl2bk3WWrFM/nIkWFCkIRgdNKk0=,tag:Of0vZwJyoWYAUjIHiQkb8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
