---
# (string) Timezone for the servers
# timezone: "America/New_York"

# (list) Additional ssh public keys to add to the nodes
# ssh_authorized_keys:

fedora:
  packages:
    - device-mapper-multipath
    - dnf-plugin-system-upgrade
    - dnf-utils
    - hdparm
    - htop
    - ipvsadm
    - iscsi-initiator-utils
    - lm_sensors
    - lsscsi
    - nano
    - nvme-cli
    - sg3_utils
    - socat
    - python3-kubernetes
    - python3-libselinux
    - python3-pyyaml

ubuntu:
  packages:
    - hdparm
    - htop
    - ipvsadm
    - lm-sensors
    - lsscsi
    - multipath-tools
    - nano
    - nfs-common
    - nvme-cli
    - open-iscsi
    - python3-kubernetes
    - python3-yaml
    - scsitools
    - sg3-utils
    - socat
