---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  KUBE_VIP_ADDR: "192.168.100.199"
  METALLB_LB_RANGE: "192.168.100.200-192.168.100.210"
  METALLB_K8S_GATEWAY_ADDR: "192.168.100.200"
  METALLB_INGRESS_ADDR: "192.168.100.201"
